# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Thuan Hoang Nguyen
name: Thuan Hoang Nguyen
position: PhD Student
email: thuan.nguyen@mbzuai.ac.ae
description: >-
  I am a PhD student at [MBZUAI](https://mbzuai.ac.ae), advised by [Prof. Hao Li](https://www.hao-li.com/Hao_Li/Hao_Li_-_about_me.html) (primary) and [Prof. Nils Lukas](https://nilslukas.github.io/).
  

  Previously, I was a research resident at [VinAI Research](https://vinai.io), where I worked under supervision of [Dr. Anh Tran](https://scholar.google.com/citations?user=FYZ5ODQAAAAJ). Before that, I recieved a B.Eng. degree in Computer Science at the [Ho Chi Minh University of Technology - VNUHCM](https://hcmut.edu.vn/en/) where I was advised by [Prof. Duc Dung Nguyen](https://scholar.google.com/citations?user=xV7uHJgAAAAJ).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thuanz123.github.io" # the base hostname & protocol for your site, e.g. http://example.com
x_username: thuanz123
github_username: thuanz123
google_scholar: 6xS-7kMAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
